[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.2",
    "numpy>=1.26.0",
    "scikit-learn>=1.4.0",
]
